output_dir: '../../data/tcell_project/split_raw_data_fish/'
module: src.pipelines.preprocessing
class: SimplePreprocessingPipeline
run_params:
  input_dir: '../../data/tcell_project/raw_data/painted_tcell_fish_data/t_cell_chr4_chr6_chr18/'


pipeline:
  - method: run_default_pipeline_lsm
    params:
      channels: ['DAPI','CHR4', 'CHR6', 'CHR18']
